[2024-05-11T23:47:28.636+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gtaV_reviews_project.load__1 manual__2024-05-11T23:47:13.481349+00:00 [queued]>
[2024-05-11T23:47:28.641+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gtaV_reviews_project.load__1 manual__2024-05-11T23:47:13.481349+00:00 [queued]>
[2024-05-11T23:47:28.642+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-05-11T23:47:28.653+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): load__1> on 2024-05-11 23:47:13.481349+00:00
[2024-05-11T23:47:28.659+0000] {standard_task_runner.py:60} INFO - Started process 1138 to run task
[2024-05-11T23:47:28.661+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gtaV_reviews_project', 'load__1', 'manual__2024-05-11T23:47:13.481349+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/gtaV_reviews_pipeline.py', '--cfg-path', '/tmp/tmplzq9g8u3']
[2024-05-11T23:47:28.662+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask load__1
[2024-05-11T23:47:28.701+0000] {task_command.py:423} INFO - Running <TaskInstance: gtaV_reviews_project.load__1 manual__2024-05-11T23:47:13.481349+00:00 [running]> on host 93cdc42157bb
[2024-05-11T23:47:28.763+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gtaV_reviews_project' AIRFLOW_CTX_TASK_ID='load__1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T23:47:13.481349+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-11T23:47:13.481349+00:00'
[2024-05-11T23:47:28.769+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gtaV_reviews_pipeline.py", line 65, in load
    cleaned_data = pd.read_csv(file_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 716, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 456, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
[2024-05-11T23:47:28.784+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=gtaV_reviews_project, task_id=load__1, execution_date=20240511T234713, start_date=20240511T234728, end_date=20240511T234728
[2024-05-11T23:47:28.795+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 29 for task load__1 (Invalid file path or buffer object type: <class 'NoneType'>; 1138)
[2024-05-11T23:47:28.835+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-11T23:47:28.847+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
